import { useEffect, useState, useContext, useCallback } from "react";
import { Link, Navigate } from "react-router-dom";
import API from "../api/axios";
import { AuthContext } from "../context/AuthContext";

// This page lets admins and managers manage allowed users.
export default function Users() {
  // This reads the logged-in user so the page can show correct permissions.
  const { user } = useContext(AuthContext);

  // This stores the users loaded from the backend.
  const [users, setUsers] = useState([]);

  // This stores the search text.
  const [search, setSearch] = useState("");

  // This stores a delayed search value so typing does not call the backend on every key.
  const [debouncedSearch, setDebouncedSearch] = useState("");

  // This stores the selected role filter.
  const [role, setRole] = useState("");

  // This stores the selected status filter.
  const [status, setStatus] = useState("");

  // This stores the current table page.
  const [page, setPage] = useState(1);

  // This stores the total number of pages from the backend.
  const [pages, setPages] = useState(1);

  // This stores which user row is currently being edited.
  const [editingId, setEditingId] = useState(null);

  // This stores the fields for the row currently being edited.
  const [editForm, setEditForm] = useState({});

  // This stores the admin create-user form; password is not included because backend generates it.
  const [newUser, setNewUser] = useState({
    name: "",
    email: "",
    role: "user",
  });

  // This waits briefly after typing before applying search for better speed.
  useEffect(() => {
    // This starts a small timer after each search change.
    const timer = setTimeout(() => {
      setDebouncedSearch(search);
    }, 350);

    // This clears the previous timer when the user keeps typing.
    return () => clearTimeout(timer);
  }, [search]);

  // This loads users from the backend using current filters.
  const fetchUsers = useCallback(async () => {
    try {
      // This asks the backend for users with pagination and filters.
      const { data } = await API.get("/users", {
        params: { page, search: debouncedSearch, role, status },
      });

      // This stores the returned users in state.
      setUsers(data.users || []);

      // This stores the total pages and keeps at least one page visible.
      setPages(data.pages || 1);
    } catch (err) {
      // This shows the backend reason if the list cannot load.
      alert(err.response?.data?.message || "Failed to fetch users");
    }
  }, [page, debouncedSearch, role, status]);

  // This reloads users when filters or page number change.
  useEffect(() => {
    fetchUsers();
  }, [fetchUsers]);

  // This blocks normal users from opening the manage users page.
  if (user?.role === "user") {
    return <Navigate to="/" />;
  }

  // This starts editing a row by copying the selected user into editForm.
  const startEdit = (selectedUser) => {
    setEditingId(selectedUser._id);
    setEditForm({
      name: selectedUser.name,
      email: selectedUser.email,
      role: selectedUser.role,
      status: selectedUser.status,
      password: "",
    });
  };

  // This cancels row editing.
  const cancelEdit = () => {
    setEditingId(null);
    setEditForm({});
  };

  // This creates a new user from the admin form.
  const createUser = async (e) => {
    e.preventDefault();

    try {
      // This sends only name, email, and role because password is generated by the backend.
      const { data } = await API.post("/users", newUser);

      // This shows the generated password one time so the admin can share it.
      alert(`User created.\nGenerated password: ${data.generatedPassword}\nThe user must change it before login.`);

      // This clears the create form after success.
      setNewUser({ name: "", email: "", role: "user" });

      // This reloads the table so the new user appears.
      fetchUsers();
    } catch (err) {
      // This shows the backend reason if create fails.
      alert(err.response?.data?.message || "Create failed");
    }
  };

  // This saves changes for the row being edited.
  const saveUser = async (id) => {
    try {
      // This starts with fields that both admin and manager may update.
      const payload = {
        name: editForm.name,
        email: editForm.email,
        status: editForm.status,
      };

      // This lets only admins send role changes.
      if (user?.role === "admin") {
        payload.role = editForm.role;
      }

      // This lets only admins send password changes, and only when typed.
      if (user?.role === "admin" && editForm.password) {
        payload.password = editForm.password;
      }

      // This sends the update to the backend.
      await API.put(`/users/${id}`, payload);

      // This exits edit mode after saving.
      cancelEdit();

      // This reloads the table with fresh data.
      fetchUsers();
    } catch (err) {
      // This shows the backend reason if update fails.
      alert(err.response?.data?.message || "Update failed");
    }
  };

  // This changes status to inactive for a user.
  const deactivateUser = async (id) => {
    // This asks for confirmation before deactivating.
    const confirmDelete = window.confirm("Deactivate this account?");
    if (!confirmDelete) return;

    try {
      // This uses the update route so managers can deactivate allowed users too.
      await API.put(`/users/${id}`, { status: "inactive" });

      // This refreshes the table after deactivation.
      fetchUsers();
    } catch (err) {
      // This shows the backend reason if deactivate fails.
      alert(err.response?.data?.message || "Deactivate failed");
    }
  };

  // This changes status to active for a user waiting for approval.
  const activateUser = async (id) => {
    try {
      // This tells the backend to activate the selected account.
      await API.put(`/users/${id}`, { status: "active" });

      // This refreshes the table after activation.
      fetchUsers();
    } catch (err) {
      // This shows the backend reason if activation fails.
      alert(err.response?.data?.message || "Activate failed");
    }
  };

  return (
    <main className="page-shell scene-shell">
      <section className="floating-panel wide-panel">
        <div className="section-heading">
          <div>
            <Link className="text-btn" to="/">Back to dashboard</Link>
            <h1>User Management</h1>
            <p className="muted-text">
              Admins control every account. Managers can update non-admin users without changing roles or passwords.
            </p>
          </div>
          <span className="role-pill">{user?.role}</span>
        </div>

        <div className="toolbar">
          <input
            className="input-3d"
            placeholder="Search name or email"
            value={search}
            onChange={(e) => {
              setPage(1);
              setSearch(e.target.value);
            }}
          />
          <select
            className="input-3d"
            value={role}
            onChange={(e) => {
              setPage(1);
              setRole(e.target.value);
            }}
          >
            <option value="">All Roles</option>
            {user?.role === "admin" && <option value="admin">Admin</option>}
            {user?.role === "admin" && <option value="manager">Manager</option>}
            <option value="user">User</option>
          </select>
          <select
            className="input-3d"
            value={status}
            onChange={(e) => {
              setPage(1);
              setStatus(e.target.value);
            }}
          >
            <option value="">All Status</option>
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>
          <button className="secondary-btn" onClick={fetchUsers}>Refresh</button>
        </div>

        {user?.role === "admin" && (
          <form className="create-strip" onSubmit={createUser}>
            <input
              className="input-3d"
              placeholder="Name"
              value={newUser.name}
              onChange={(e) => setNewUser({ ...newUser, name: e.target.value })}
            />
            <input
              className="input-3d"
              placeholder="Email"
              value={newUser.email}
              onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}
            />
            <select
              className="input-3d"
              value={newUser.role}
              onChange={(e) => setNewUser({ ...newUser, role: e.target.value })}
            >
              <option value="user">User</option>
              <option value="manager">Manager</option>
            </select>
            <button className="primary-btn" type="submit">Add User</button>
          </form>
        )}

        <div className="table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                {user?.role === "admin" && <th>Password</th>}
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {users.length === 0 ? (
                <tr>
                  <td colSpan={user?.role === "admin" ? 6 : 5} className="empty-cell">
                    No users found
                  </td>
                </tr>
              ) : (
                users.map((listedUser) => {
                  // This checks if the current row is in edit mode.
                  const isEditing = editingId === listedUser._id;

                  // This stops managers from editing anything except normal user rows.
                  const managerBlocked = user?.role === "manager" && listedUser.role !== "user";

                  return (
                    <tr key={listedUser._id}>
                      <td>
                        {isEditing ? (
                          <input
                            className="table-input"
                            value={editForm.name}
                            onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                          />
                        ) : (
                          listedUser.name
                        )}
                      </td>
                      <td>
                        {isEditing ? (
                          <input
                            className="table-input"
                            value={editForm.email}
                            onChange={(e) => setEditForm({ ...editForm, email: e.target.value })}
                          />
                        ) : (
                          listedUser.email
                        )}
                      </td>
                      <td>
                        {isEditing && user?.role === "admin" ? (
                          <select
                            className="table-input"
                            value={editForm.role}
                            onChange={(e) => setEditForm({ ...editForm, role: e.target.value })}
                          >
                            <option value="admin">Admin</option>
                            <option value="manager">Manager</option>
                            <option value="user">User</option>
                          </select>
                        ) : (
                          listedUser.role
                        )}
                      </td>
                      <td>
                        {isEditing ? (
                          <select
                            className="table-input"
                            value={editForm.status}
                            onChange={(e) => setEditForm({ ...editForm, status: e.target.value })}
                          >
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                          </select>
                        ) : (
                          <span className={listedUser.status === "active" ? "status good" : "status bad"}>
                            {listedUser.status}
                          </span>
                        )}
                      </td>
                      {user?.role === "admin" && (
                        <td>
                          {isEditing ? (
                            <input
                              className="table-input"
                              type="password"
                              placeholder="Optional"
                              value={editForm.password}
                              onChange={(e) => setEditForm({ ...editForm, password: e.target.value })}
                            />
                          ) : (
                            listedUser.passwordChangeRequired ? "Change required" : "Protected"
                          )}
                        </td>
                      )}
                      <td>
                        <div className="action-row">
                          {isEditing ? (
                            <>
                              <button className="small-btn" onClick={() => saveUser(listedUser._id)}>Save</button>
                              <button className="small-btn ghost" onClick={cancelEdit}>Cancel</button>
                            </>
                          ) : (
                            <>
                              {!managerBlocked && (
                                <button className="small-btn" onClick={() => startEdit(listedUser)}>Edit</button>
                              )}
                              {!managerBlocked && listedUser.status === "active" && (
                                <button className="small-btn danger" onClick={() => deactivateUser(listedUser._id)}>
                                  Deactivate
                                </button>
                              )}
                              {!managerBlocked && listedUser.status === "inactive" && (
                                <button className="small-btn" onClick={() => activateUser(listedUser._id)}>
                                  Activate
                                </button>
                              )}
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>

        <div className="pagination">
          <button className="secondary-btn" onClick={() => setPage((p) => Math.max(p - 1, 1))}>
            Prev
          </button>
          <span>Page {page} of {pages}</span>
          <button className="secondary-btn" onClick={() => setPage((p) => Math.min(p + 1, pages))}>
            Next
          </button>
        </div>
      </section>
    </main>
  );
}
